name: Deploy

on:
  repository_dispatch:
    types: [BACKEND_TEST_FINISH_TRIGGER]

env:
  DOCKER_IMAGE: ghcr.io/eddi-robotacademy/d-yes-backend/team-project-backend
  VERSION: ${{ github.sha }}
  NAME: team-project-backend

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'zulu' # https://github.com/actions/setup-java

        - name: Gradle Caching
          uses: actions/cache@v3
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
              
        - name: create application.properties for CD
          run: |
            mkdir -p src/main/resources
            cd src/main/resources
            echo "${{ secrets.DEPLOY_APPLICATION_PROPERTIES }}" > application.properties
            echo "${{ secrets.DEPLOY_MYSQL_PROPERTIES }}" >> application.properties
            echo "${{ secrets.DEPLOY_REDIS_PROPERTIES }}" >> application.properties
            echo "${{ secrets.DEPLOY_CORS_PROPERTIES }}" >> application.properties
            echo "${{ secrets.DEPLOY_GOOGLE_CONFIG }}" >> application.properties
            echo "${{ secrets.DEPLOY_KAKAO_CONFIG }}" >> application.properties
            echo "${{ secrets.DEPLOY_NAVER_CONFIG }}" >> application.properties
            echo "${{ secrets.DEPLOY_KAKAO_PAYMENT_PROPERTIES }}" >> application.properties
            echo "${{ secrets.DEPLOY_FASTAPI_CONFIG }}" >> application.properties
            ls

        - name: Grant Permission to gradlew
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew clean build -x test

        - name: Docker build & push to prod
          run: |
              docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
              docker buildx create --name arm64builder --use
              docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t ghcr.io/eddi-robotacademy/d-yes-backend/team-project-backend:latest --push .
              docker logout

  deploy:
    name: Deploy
    needs: build
    runs-on: [ self-hosted, deploy-d-yes-backend ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Deploy to prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: |
            pwd
            ls -al
            cd d-yes/backend-spring/actions-runner
            pwd

            if [[ "$(docker ps -q --filter ancestor=mysql:8.0)" ]]; then
              docker rm -f $(docker ps -qa --filter ancestor=mysql:8.0)
            fi
            echo "pass mysql-container"

            if [[ "$(docker ps -qa --filter ancestor=team-project-backend/d-yes-backend-server:latest)" ]]; then
              docker rm -f $(docker ps -qa --filter ancestor=team-project-backend/d-yes-backend-server:latest)
            fi
            echo "pass team-project-backend/d-yes-backend-server:latest"
  
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}

            docker pull ghcr.io/eddi-robotacademy/d-yes-backend/team-project-backend:latest

            docker image prune -f
            docker logout
            docker-compose up -d
